version: '3'
services:

  #web:
    #image: auryum/iknowit:web

  api:
    image: auryum/iknowit:api
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure

  mysql:
    image: auryum/iknowit:mysql
    ports:
      - "3307:3306"
    #volumes:
      #- db-data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: senhaFiap
       MYSQL_USER: root
       MYSQL_DATABASE: iknowitdb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

#volumes:
  #db-data: