version: '3'
services:

  #web:
    #image: auryum/iknowit:web

  api:
    image: auryum/iknowit:api
    ports:
      - "5000:5000"
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: auryum/iknowit:mysql
    ports:
      - "3307:3306"
    #volumes:
    #  - /var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: senhaFiap
       MYSQL_USER: root
       MYSQL_DATABASE: iknowitdb
