version: '3.2'
services:

  web:
    image: auryum/iknowit:webweb
    ports:
      - "32768:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  api:
    image: auryum/iknowit:apiweb
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    deploy:
      replicas: 3
      mode: replicated
      restart_policy:
        condition: on-failure

  mysql:
    image: auryum/iknowit:mysql
    ports:
      - "3307:3306"
    #volumes:
      #- db-data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: senhaFiap
       MYSQL_USER: root
       MYSQL_DATABASE: iknowitdb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

#volumes:
  #db-data: